### ISSUE TITLE
I've got an error on start

### ISSUE THREAD

**Issue by sovietspy2** [amandeepmittal/apollo-express-demo#2]
Node v: v10.15.3
OS: windows 10

I ran npm install and then npm start and it produced this error. As far as I can tell the problem is the ESM imports. How am I supposed to run the code? Can you please add a readme with few instructions? Thank you very much. 

```
C:\...\apollo-express-demo>npm start

> apollo-express-demo@0.0.1 start C:\...\apollo-express-demo
> node index.js

C:\...\apollo-express-demo\index.js:1
(function (exports, require, module, __filename, __dirname) { import express from 'express';
                                                                     ^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apollo-express-demo@0.0.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the apollo-express-demo@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```
I also tried npm run dev but that gave other errors with babel. 
`Babel compilation error TypeError: Cannot read property 'bindings' of null`
Babel version mismatch?

**Comment by amandeepmittal** [comment]
Hi @sovietspy2, you to configure babel to use ES6 import/export statements and run `npm run dev` instead of `npm start` for babel to watch files.

**Comment by sovietspy2** [comment]
Yeah that helped me. Thanks
